name: Rust

on:
  pull_request:
    branches:
    - master

jobs:
  build_and_test:
    name: Builds and tests Rust (stable) on ${{ matrix.os }}    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
